import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Container, Background } from "../components/LogIn/style";
import Sidebar from "../components/LogIn/Sidebar";
import { useQuery } from "react-query";
import * as Services from "../services";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const [loginFormData, setFormData] = useState({ email: "", password: "" });
  const router = useRouter();
  const handleUpdateLoginForm = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...loginFormData, [e.target.name]: e.target.value });
  };

  const { isSuccess, data, isLoading, isError, refetch, error } = useQuery(
    ["authUser"],
    () => Services.login(loginFormData),
    {
      enabled: false,
      refetchOnWindowFocus: false,
    }
  );

  useEffect(() => {
    if (isSuccess) {
      localStorage.setItem("jwttoken", data.data.jwt);
     
      router.push("/profile");
    }
  }, [isSuccess, data]);

  const handleLogin = () => {
    refetch();
  };
  return (
    <>
      <Head>
        <title>Log In | My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Login /> */}
      <Container>
        <Sidebar
          loginFormData={loginFormData}
          handleUpdate={handleUpdateLoginForm}
          handleLogin={handleLogin}
          isLoading={isLoading}
          isError={isError}
          error={error?.response?.data.message}
        />
        <Background />
      </Container>
    </>
  );
};

export default Login;
