import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/LogIn'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Log In | My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Login />
    </>
  )
}

export default Home
