import type { NextPage } from "next";
import Head from "next/head";
import UserProfile from "../components/Profile";
const Profile: NextPage = () => {
  return (
    <>
      <Head>
        <title>Profile | My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserProfile
        profileData={{
          email: "aguiarf.j16@gmail.com",
          username: "jesusaguiar",
          age: "24",
        }}
      />
    </>
  );
};

export default Profile;
